name: 'c4o-core'
description: 'Unified EDA Toolchain for Chip Design'
author: 'c4o'

inputs:
  command:
    description: 'The subcommand to run (lint, sim, synth, gds)'
    required: true
  files:
    description: 'Path to Verilog files (optional if using src/config.json)'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - '--files'
    - ${{ inputs.files }}
